package day12;

public class Exception01 {

	public static void main(String[] args) {
		/* Exception : 예외 처리
		 * 실행 시 발생할 수 있는 예외를 처리하여 정상처리로 유지시키는 기능
		 * try ~ catch(필수) ~ finally(선택)
		 * try : 예외가 발생할 가능성이 있는 구문 작성
		 * catch : try 구문에서 예외가 발생했을 때 예외처리
		 * finally : try 구문외 반드시 실행되어야 하는 구문이 있을 경우 (없으면 사용 X)
		 */
		
		double res = 0;
		
		int num = 10;
		int num1 = 0;
		
		res = num / num1;

	}

}
